/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as OnboardingRouteImport } from "./routes/onboarding";
import { Route as PlatformRouteImport } from "./routes/platform";
import { Route as PricingRouteImport } from "./routes/pricing";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as ResetPasswordRouteImport } from "./routes/reset-password";
import { Route as VerifyEmailRouteImport } from "./routes/verify-email";
import { Route as BookSlugRouteImport } from "./routes/book.$slug";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard.index";
import { Route as DashboardAppointmentsRouteImport } from "./routes/dashboard.appointments";
import { Route as DashboardAuditLogRouteImport } from "./routes/dashboard.audit-log";
import { Route as DashboardBillingRouteImport } from "./routes/dashboard.billing";
import { Route as DashboardChartSearchRouteImport } from "./routes/dashboard.chart-search";
import { Route as DashboardDocumentsRouteImport } from "./routes/dashboard.documents";
import { Route as DashboardInsightsRouteImport } from "./routes/dashboard.insights";
import { Route as DashboardNotificationsRouteImport } from "./routes/dashboard.notifications";
import { Route as DashboardOutreachRouteImport } from "./routes/dashboard.outreach";
import { Route as DashboardRecallsRouteImport } from "./routes/dashboard.recalls";
import { Route as DashboardRemindersRouteImport } from "./routes/dashboard.reminders";
import { Route as DashboardReportsRouteImport } from "./routes/dashboard.reports";
import { Route as DashboardSettingsRouteImport } from "./routes/dashboard.settings";
import { Route as DashboardWaitingRoomRouteImport } from "./routes/dashboard.waiting-room";
import { Route as InvitationsAcceptRouteImport } from "./routes/invitations.accept";
import { Route as NpsTokenRouteImport } from "./routes/nps.$token";
import { Route as PlatformIndexRouteImport } from "./routes/platform.index";
import { Route as PlatformFlagsRouteImport } from "./routes/platform.flags";
import { Route as PlatformMetricsRouteImport } from "./routes/platform.metrics";
import { Route as ReferralChartTokenRouteImport } from "./routes/referral-chart.$token";
import { Route as RemindersTokenRouteImport } from "./routes/reminders.$token";
import { Route as DashboardAppointmentsIndexRouteImport } from "./routes/dashboard.appointments.index";
import { Route as DashboardAppointmentsCalendarRouteImport } from "./routes/dashboard.appointments.calendar";
import { Route as DashboardAppointmentsNewRouteImport } from "./routes/dashboard.appointments.new";
import { Route as DashboardBillingIndexRouteImport } from "./routes/dashboard.billing.index";
import { Route as DashboardBillingClaimsRouteImport } from "./routes/dashboard.billing.claims";
import { Route as DashboardBillingEligibilityRouteImport } from "./routes/dashboard.billing.eligibility";
import { Route as DashboardBillingInvoicesRouteImport } from "./routes/dashboard.billing.invoices";
import { Route as DashboardBillingLoaRouteImport } from "./routes/dashboard.billing.loa";
import { Route as DashboardDocumentsIndexRouteImport } from "./routes/dashboard.documents.index";
import { Route as DashboardDocumentsGenerateRouteImport } from "./routes/dashboard.documents.generate";
import { Route as DashboardDocumentsTemplatesRouteImport } from "./routes/dashboard.documents.templates";
import { Route as DashboardInsightsIndexRouteImport } from "./routes/dashboard.insights.index";
import { Route as DashboardInsightsAuditLogRouteImport } from "./routes/dashboard.insights.audit-log";
import { Route as DashboardInsightsReportsRouteImport } from "./routes/dashboard.insights.reports";
import { Route as DashboardOutreachIndexRouteImport } from "./routes/dashboard.outreach.index";
import { Route as DashboardOutreachRecallsRouteImport } from "./routes/dashboard.outreach.recalls";
import { Route as DashboardOutreachRemindersRouteImport } from "./routes/dashboard.outreach.reminders";
import { Route as DashboardPatientsIndexRouteImport } from "./routes/dashboard.patients.index";
import { Route as DashboardPatientsPatientIdRouteImport } from "./routes/dashboard.patients.$patientId";
import { Route as DashboardPatientsChartSearchRouteImport } from "./routes/dashboard.patients.chart-search";
import { Route as DashboardPatientsNewRouteImport } from "./routes/dashboard.patients.new";
import { Route as DashboardSettingsIndexRouteImport } from "./routes/dashboard.settings.index";
import { Route as DashboardSettingsAccountRouteImport } from "./routes/dashboard.settings.account";
import { Route as DashboardSettingsAssistantRouteImport } from "./routes/dashboard.settings.assistant";
import { Route as DashboardSettingsClinicRouteImport } from "./routes/dashboard.settings.clinic";
import { Route as DashboardSettingsDoctorRouteImport } from "./routes/dashboard.settings.doctor";
import { Route as DashboardSettingsDocumentTemplatesRouteImport } from "./routes/dashboard.settings.document-templates";
import { Route as DashboardSettingsMembershipPlansRouteImport } from "./routes/dashboard.settings.membership-plans";
import { Route as DashboardSettingsNotificationsRouteImport } from "./routes/dashboard.settings.notifications";
import { Route as DashboardSettingsOrganizationRouteImport } from "./routes/dashboard.settings.organization";
import { Route as DashboardSettingsPayersRouteImport } from "./routes/dashboard.settings.payers";
import { Route as DashboardSettingsPlanRouteImport } from "./routes/dashboard.settings.plan";
import { Route as DashboardSettingsServicesRouteImport } from "./routes/dashboard.settings.services";
import { Route as DashboardSettingsTeamRouteImport } from "./routes/dashboard.settings.team";
import { Route as PatientPortalSlugIndexRouteImport } from "./routes/patient-portal.$slug.index";
import { Route as PatientPortalSlugChartRouteImport } from "./routes/patient-portal.$slug.chart";
import { Route as PatientPortalSlugDocumentsRouteImport } from "./routes/patient-portal.$slug.documents";
import { Route as PatientPortalSlugInvoicesRouteImport } from "./routes/patient-portal.$slug.invoices";
import { Route as PatientPortalSlugLoginRouteImport } from "./routes/patient-portal.$slug.login";
import { Route as PatientPortalSlugVerifyRouteImport } from "./routes/patient-portal.$slug.verify";
import { Route as PatientPortalSlugVisitsRouteImport } from "./routes/patient-portal.$slug.visits";
import { Route as PlatformTenantsClinicIdRouteImport } from "./routes/platform.tenants.$clinicId";
import { Route as DashboardAppointmentsAppointmentIdSoapRouteImport } from "./routes/dashboard.appointments.$appointmentId.soap";
import { Route as DashboardBillingClaimsClaimIdRouteImport } from "./routes/dashboard.billing.claims.$claimId";
import { Route as DashboardPatientsPatientIdIndexRouteImport } from "./routes/dashboard.patients.$patientId.index";
import { Route as DashboardPatientsPatientIdActivityRouteImport } from "./routes/dashboard.patients.$patientId.activity";
import { Route as DashboardPatientsPatientIdBillingRouteImport } from "./routes/dashboard.patients.$patientId.billing";
import { Route as DashboardPatientsPatientIdDocumentsRouteImport } from "./routes/dashboard.patients.$patientId.documents";
import { Route as DashboardPatientsPatientIdOrdersRouteImport } from "./routes/dashboard.patients.$patientId.orders";
import { Route as DashboardPatientsPatientIdPrescriptionsRouteImport } from "./routes/dashboard.patients.$patientId.prescriptions";
import { Route as DashboardPatientsPatientIdTimelineRouteImport } from "./routes/dashboard.patients.$patientId.timeline";
import { Route as DashboardSettingsClinicIndexRouteImport } from "./routes/dashboard.settings.clinic.index";
import { Route as DashboardSettingsClinicBrandingRouteImport } from "./routes/dashboard.settings.clinic.branding";
import { Route as DashboardSettingsClinicComplianceRouteImport } from "./routes/dashboard.settings.clinic.compliance";
import { Route as DashboardSettingsClinicDetailsRouteImport } from "./routes/dashboard.settings.clinic.details";
import { Route as DashboardSettingsClinicHoursRouteImport } from "./routes/dashboard.settings.clinic.hours";
import { Route as DashboardSettingsClinicRoomsRouteImport } from "./routes/dashboard.settings.clinic.rooms";
import { Route as DashboardPatientsPatientIdDocumentsNewRouteImport } from "./routes/dashboard.patients.$patientId.documents.new";
import { Route as DashboardPatientsPatientIdInvoicesInvoiceIdRouteImport } from "./routes/dashboard.patients.$patientId.invoices.$invoiceId";
import { Route as DashboardPatientsPatientIdInvoicesNewRouteImport } from "./routes/dashboard.patients.$patientId.invoices.new";
import { Route as DashboardPatientsPatientIdPrescriptionsNewRouteImport } from "./routes/dashboard.patients.$patientId.prescriptions.new";
import { Route as DashboardSettingsOrganizationClinicsNewRouteImport } from "./routes/dashboard.settings.organization.clinics.new";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformRoute = PlatformRouteImport.update({
  id: "/platform",
  path: "/platform",
  getParentRoute: () => rootRouteImport,
} as any);
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any);
const BookSlugRoute = BookSlugRouteImport.update({
  id: "/book/$slug",
  path: "/book/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: "/appointments",
  path: "/appointments",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: "/audit-log",
  path: "/audit-log",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardChartSearchRoute = DashboardChartSearchRouteImport.update({
  id: "/chart-search",
  path: "/chart-search",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: "/insights",
  path: "/insights",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: "/outreach",
  path: "/outreach",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardRecallsRoute = DashboardRecallsRouteImport.update({
  id: "/recalls",
  path: "/recalls",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardRemindersRoute = DashboardRemindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardWaitingRoomRoute = DashboardWaitingRoomRouteImport.update({
  id: "/waiting-room",
  path: "/waiting-room",
  getParentRoute: () => DashboardRoute,
} as any);
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: "/invitations/accept",
  path: "/invitations/accept",
  getParentRoute: () => rootRouteImport,
} as any);
const NpsTokenRoute = NpsTokenRouteImport.update({
  id: "/nps/$token",
  path: "/nps/$token",
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PlatformRoute,
} as any);
const PlatformFlagsRoute = PlatformFlagsRouteImport.update({
  id: "/flags",
  path: "/flags",
  getParentRoute: () => PlatformRoute,
} as any);
const PlatformMetricsRoute = PlatformMetricsRouteImport.update({
  id: "/metrics",
  path: "/metrics",
  getParentRoute: () => PlatformRoute,
} as any);
const ReferralChartTokenRoute = ReferralChartTokenRouteImport.update({
  id: "/referral-chart/$token",
  path: "/referral-chart/$token",
  getParentRoute: () => rootRouteImport,
} as any);
const RemindersTokenRoute = RemindersTokenRouteImport.update({
  id: "/reminders/$token",
  path: "/reminders/$token",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any);
const DashboardAppointmentsCalendarRoute =
  DashboardAppointmentsCalendarRouteImport.update({
    id: "/calendar",
    path: "/calendar",
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any);
const DashboardAppointmentsNewRoute =
  DashboardAppointmentsNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any);
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardBillingRoute,
} as any);
const DashboardBillingClaimsRoute = DashboardBillingClaimsRouteImport.update({
  id: "/claims",
  path: "/claims",
  getParentRoute: () => DashboardBillingRoute,
} as any);
const DashboardBillingEligibilityRoute =
  DashboardBillingEligibilityRouteImport.update({
    id: "/eligibility",
    path: "/eligibility",
    getParentRoute: () => DashboardBillingRoute,
  } as any);
const DashboardBillingInvoicesRoute =
  DashboardBillingInvoicesRouteImport.update({
    id: "/invoices",
    path: "/invoices",
    getParentRoute: () => DashboardBillingRoute,
  } as any);
const DashboardBillingLoaRoute = DashboardBillingLoaRouteImport.update({
  id: "/loa",
  path: "/loa",
  getParentRoute: () => DashboardBillingRoute,
} as any);
const DashboardDocumentsIndexRoute = DashboardDocumentsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardDocumentsRoute,
} as any);
const DashboardDocumentsGenerateRoute =
  DashboardDocumentsGenerateRouteImport.update({
    id: "/generate",
    path: "/generate",
    getParentRoute: () => DashboardDocumentsRoute,
  } as any);
const DashboardDocumentsTemplatesRoute =
  DashboardDocumentsTemplatesRouteImport.update({
    id: "/templates",
    path: "/templates",
    getParentRoute: () => DashboardDocumentsRoute,
  } as any);
const DashboardInsightsIndexRoute = DashboardInsightsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardInsightsRoute,
} as any);
const DashboardInsightsAuditLogRoute =
  DashboardInsightsAuditLogRouteImport.update({
    id: "/audit-log",
    path: "/audit-log",
    getParentRoute: () => DashboardInsightsRoute,
  } as any);
const DashboardInsightsReportsRoute =
  DashboardInsightsReportsRouteImport.update({
    id: "/reports",
    path: "/reports",
    getParentRoute: () => DashboardInsightsRoute,
  } as any);
const DashboardOutreachIndexRoute = DashboardOutreachIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardOutreachRoute,
} as any);
const DashboardOutreachRecallsRoute =
  DashboardOutreachRecallsRouteImport.update({
    id: "/recalls",
    path: "/recalls",
    getParentRoute: () => DashboardOutreachRoute,
  } as any);
const DashboardOutreachRemindersRoute =
  DashboardOutreachRemindersRouteImport.update({
    id: "/reminders",
    path: "/reminders",
    getParentRoute: () => DashboardOutreachRoute,
  } as any);
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: "/patients/",
  path: "/patients/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardPatientsPatientIdRoute =
  DashboardPatientsPatientIdRouteImport.update({
    id: "/patients/$patientId",
    path: "/patients/$patientId",
    getParentRoute: () => DashboardRoute,
  } as any);
const DashboardPatientsChartSearchRoute =
  DashboardPatientsChartSearchRouteImport.update({
    id: "/patients/chart-search",
    path: "/patients/chart-search",
    getParentRoute: () => DashboardRoute,
  } as any);
const DashboardPatientsNewRoute = DashboardPatientsNewRouteImport.update({
  id: "/patients/new",
  path: "/patients/new",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardSettingsRoute,
} as any);
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: "/account",
    path: "/account",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsAssistantRoute =
  DashboardSettingsAssistantRouteImport.update({
    id: "/assistant",
    path: "/assistant",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsClinicRoute = DashboardSettingsClinicRouteImport.update({
  id: "/clinic",
  path: "/clinic",
  getParentRoute: () => DashboardSettingsRoute,
} as any);
const DashboardSettingsDoctorRoute = DashboardSettingsDoctorRouteImport.update({
  id: "/doctor",
  path: "/doctor",
  getParentRoute: () => DashboardSettingsRoute,
} as any);
const DashboardSettingsDocumentTemplatesRoute =
  DashboardSettingsDocumentTemplatesRouteImport.update({
    id: "/document-templates",
    path: "/document-templates",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsMembershipPlansRoute =
  DashboardSettingsMembershipPlansRouteImport.update({
    id: "/membership-plans",
    path: "/membership-plans",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: "/organization",
    path: "/organization",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsPayersRoute = DashboardSettingsPayersRouteImport.update({
  id: "/payers",
  path: "/payers",
  getParentRoute: () => DashboardSettingsRoute,
} as any);
const DashboardSettingsPlanRoute = DashboardSettingsPlanRouteImport.update({
  id: "/plan",
  path: "/plan",
  getParentRoute: () => DashboardSettingsRoute,
} as any);
const DashboardSettingsServicesRoute =
  DashboardSettingsServicesRouteImport.update({
    id: "/services",
    path: "/services",
    getParentRoute: () => DashboardSettingsRoute,
  } as any);
const DashboardSettingsTeamRoute = DashboardSettingsTeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => DashboardSettingsRoute,
} as any);
const PatientPortalSlugIndexRoute = PatientPortalSlugIndexRouteImport.update({
  id: "/patient-portal/$slug/",
  path: "/patient-portal/$slug/",
  getParentRoute: () => rootRouteImport,
} as any);
const PatientPortalSlugChartRoute = PatientPortalSlugChartRouteImport.update({
  id: "/patient-portal/$slug/chart",
  path: "/patient-portal/$slug/chart",
  getParentRoute: () => rootRouteImport,
} as any);
const PatientPortalSlugDocumentsRoute =
  PatientPortalSlugDocumentsRouteImport.update({
    id: "/patient-portal/$slug/documents",
    path: "/patient-portal/$slug/documents",
    getParentRoute: () => rootRouteImport,
  } as any);
const PatientPortalSlugInvoicesRoute =
  PatientPortalSlugInvoicesRouteImport.update({
    id: "/patient-portal/$slug/invoices",
    path: "/patient-portal/$slug/invoices",
    getParentRoute: () => rootRouteImport,
  } as any);
const PatientPortalSlugLoginRoute = PatientPortalSlugLoginRouteImport.update({
  id: "/patient-portal/$slug/login",
  path: "/patient-portal/$slug/login",
  getParentRoute: () => rootRouteImport,
} as any);
const PatientPortalSlugVerifyRoute = PatientPortalSlugVerifyRouteImport.update({
  id: "/patient-portal/$slug/verify",
  path: "/patient-portal/$slug/verify",
  getParentRoute: () => rootRouteImport,
} as any);
const PatientPortalSlugVisitsRoute = PatientPortalSlugVisitsRouteImport.update({
  id: "/patient-portal/$slug/visits",
  path: "/patient-portal/$slug/visits",
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformTenantsClinicIdRoute = PlatformTenantsClinicIdRouteImport.update({
  id: "/tenants/$clinicId",
  path: "/tenants/$clinicId",
  getParentRoute: () => PlatformRoute,
} as any);
const DashboardAppointmentsAppointmentIdSoapRoute =
  DashboardAppointmentsAppointmentIdSoapRouteImport.update({
    id: "/$appointmentId/soap",
    path: "/$appointmentId/soap",
    getParentRoute: () => DashboardAppointmentsRoute,
  } as any);
const DashboardBillingClaimsClaimIdRoute =
  DashboardBillingClaimsClaimIdRouteImport.update({
    id: "/$claimId",
    path: "/$claimId",
    getParentRoute: () => DashboardBillingClaimsRoute,
  } as any);
const DashboardPatientsPatientIdIndexRoute =
  DashboardPatientsPatientIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdActivityRoute =
  DashboardPatientsPatientIdActivityRouteImport.update({
    id: "/activity",
    path: "/activity",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdBillingRoute =
  DashboardPatientsPatientIdBillingRouteImport.update({
    id: "/billing",
    path: "/billing",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdDocumentsRoute =
  DashboardPatientsPatientIdDocumentsRouteImport.update({
    id: "/documents",
    path: "/documents",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdOrdersRoute =
  DashboardPatientsPatientIdOrdersRouteImport.update({
    id: "/orders",
    path: "/orders",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdPrescriptionsRoute =
  DashboardPatientsPatientIdPrescriptionsRouteImport.update({
    id: "/prescriptions",
    path: "/prescriptions",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdTimelineRoute =
  DashboardPatientsPatientIdTimelineRouteImport.update({
    id: "/timeline",
    path: "/timeline",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardSettingsClinicIndexRoute =
  DashboardSettingsClinicIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardSettingsClinicRoute,
  } as any);
const DashboardSettingsClinicBrandingRoute =
  DashboardSettingsClinicBrandingRouteImport.update({
    id: "/branding",
    path: "/branding",
    getParentRoute: () => DashboardSettingsClinicRoute,
  } as any);
const DashboardSettingsClinicComplianceRoute =
  DashboardSettingsClinicComplianceRouteImport.update({
    id: "/compliance",
    path: "/compliance",
    getParentRoute: () => DashboardSettingsClinicRoute,
  } as any);
const DashboardSettingsClinicDetailsRoute =
  DashboardSettingsClinicDetailsRouteImport.update({
    id: "/details",
    path: "/details",
    getParentRoute: () => DashboardSettingsClinicRoute,
  } as any);
const DashboardSettingsClinicHoursRoute =
  DashboardSettingsClinicHoursRouteImport.update({
    id: "/hours",
    path: "/hours",
    getParentRoute: () => DashboardSettingsClinicRoute,
  } as any);
const DashboardSettingsClinicRoomsRoute =
  DashboardSettingsClinicRoomsRouteImport.update({
    id: "/rooms",
    path: "/rooms",
    getParentRoute: () => DashboardSettingsClinicRoute,
  } as any);
const DashboardPatientsPatientIdDocumentsNewRoute =
  DashboardPatientsPatientIdDocumentsNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => DashboardPatientsPatientIdDocumentsRoute,
  } as any);
const DashboardPatientsPatientIdInvoicesInvoiceIdRoute =
  DashboardPatientsPatientIdInvoicesInvoiceIdRouteImport.update({
    id: "/invoices/$invoiceId",
    path: "/invoices/$invoiceId",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdInvoicesNewRoute =
  DashboardPatientsPatientIdInvoicesNewRouteImport.update({
    id: "/invoices/new",
    path: "/invoices/new",
    getParentRoute: () => DashboardPatientsPatientIdRoute,
  } as any);
const DashboardPatientsPatientIdPrescriptionsNewRoute =
  DashboardPatientsPatientIdPrescriptionsNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => DashboardPatientsPatientIdPrescriptionsRoute,
  } as any);
const DashboardSettingsOrganizationClinicsNewRoute =
  DashboardSettingsOrganizationClinicsNewRouteImport.update({
    id: "/clinics/new",
    path: "/clinics/new",
    getParentRoute: () => DashboardSettingsOrganizationRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/platform": typeof PlatformRouteWithChildren;
  "/pricing": typeof PricingRoute;
  "/register": typeof RegisterRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/book/$slug": typeof BookSlugRoute;
  "/dashboard/appointments": typeof DashboardAppointmentsRouteWithChildren;
  "/dashboard/audit-log": typeof DashboardAuditLogRoute;
  "/dashboard/billing": typeof DashboardBillingRouteWithChildren;
  "/dashboard/chart-search": typeof DashboardChartSearchRoute;
  "/dashboard/documents": typeof DashboardDocumentsRouteWithChildren;
  "/dashboard/insights": typeof DashboardInsightsRouteWithChildren;
  "/dashboard/notifications": typeof DashboardNotificationsRoute;
  "/dashboard/outreach": typeof DashboardOutreachRouteWithChildren;
  "/dashboard/recalls": typeof DashboardRecallsRoute;
  "/dashboard/reminders": typeof DashboardRemindersRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRouteWithChildren;
  "/dashboard/waiting-room": typeof DashboardWaitingRoomRoute;
  "/invitations/accept": typeof InvitationsAcceptRoute;
  "/nps/$token": typeof NpsTokenRoute;
  "/platform/flags": typeof PlatformFlagsRoute;
  "/platform/metrics": typeof PlatformMetricsRoute;
  "/referral-chart/$token": typeof ReferralChartTokenRoute;
  "/reminders/$token": typeof RemindersTokenRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/platform/": typeof PlatformIndexRoute;
  "/dashboard/appointments/calendar": typeof DashboardAppointmentsCalendarRoute;
  "/dashboard/appointments/new": typeof DashboardAppointmentsNewRoute;
  "/dashboard/billing/claims": typeof DashboardBillingClaimsRouteWithChildren;
  "/dashboard/billing/eligibility": typeof DashboardBillingEligibilityRoute;
  "/dashboard/billing/invoices": typeof DashboardBillingInvoicesRoute;
  "/dashboard/billing/loa": typeof DashboardBillingLoaRoute;
  "/dashboard/documents/generate": typeof DashboardDocumentsGenerateRoute;
  "/dashboard/documents/templates": typeof DashboardDocumentsTemplatesRoute;
  "/dashboard/insights/audit-log": typeof DashboardInsightsAuditLogRoute;
  "/dashboard/insights/reports": typeof DashboardInsightsReportsRoute;
  "/dashboard/outreach/recalls": typeof DashboardOutreachRecallsRoute;
  "/dashboard/outreach/reminders": typeof DashboardOutreachRemindersRoute;
  "/dashboard/patients/$patientId": typeof DashboardPatientsPatientIdRouteWithChildren;
  "/dashboard/patients/chart-search": typeof DashboardPatientsChartSearchRoute;
  "/dashboard/patients/new": typeof DashboardPatientsNewRoute;
  "/dashboard/settings/account": typeof DashboardSettingsAccountRoute;
  "/dashboard/settings/assistant": typeof DashboardSettingsAssistantRoute;
  "/dashboard/settings/clinic": typeof DashboardSettingsClinicRouteWithChildren;
  "/dashboard/settings/doctor": typeof DashboardSettingsDoctorRoute;
  "/dashboard/settings/document-templates": typeof DashboardSettingsDocumentTemplatesRoute;
  "/dashboard/settings/membership-plans": typeof DashboardSettingsMembershipPlansRoute;
  "/dashboard/settings/notifications": typeof DashboardSettingsNotificationsRoute;
  "/dashboard/settings/organization": typeof DashboardSettingsOrganizationRouteWithChildren;
  "/dashboard/settings/payers": typeof DashboardSettingsPayersRoute;
  "/dashboard/settings/plan": typeof DashboardSettingsPlanRoute;
  "/dashboard/settings/services": typeof DashboardSettingsServicesRoute;
  "/dashboard/settings/team": typeof DashboardSettingsTeamRoute;
  "/patient-portal/$slug/chart": typeof PatientPortalSlugChartRoute;
  "/patient-portal/$slug/documents": typeof PatientPortalSlugDocumentsRoute;
  "/patient-portal/$slug/invoices": typeof PatientPortalSlugInvoicesRoute;
  "/patient-portal/$slug/login": typeof PatientPortalSlugLoginRoute;
  "/patient-portal/$slug/verify": typeof PatientPortalSlugVerifyRoute;
  "/patient-portal/$slug/visits": typeof PatientPortalSlugVisitsRoute;
  "/platform/tenants/$clinicId": typeof PlatformTenantsClinicIdRoute;
  "/dashboard/appointments/": typeof DashboardAppointmentsIndexRoute;
  "/dashboard/billing/": typeof DashboardBillingIndexRoute;
  "/dashboard/documents/": typeof DashboardDocumentsIndexRoute;
  "/dashboard/insights/": typeof DashboardInsightsIndexRoute;
  "/dashboard/outreach/": typeof DashboardOutreachIndexRoute;
  "/dashboard/patients/": typeof DashboardPatientsIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/patient-portal/$slug/": typeof PatientPortalSlugIndexRoute;
  "/dashboard/appointments/$appointmentId/soap": typeof DashboardAppointmentsAppointmentIdSoapRoute;
  "/dashboard/billing/claims/$claimId": typeof DashboardBillingClaimsClaimIdRoute;
  "/dashboard/patients/$patientId/activity": typeof DashboardPatientsPatientIdActivityRoute;
  "/dashboard/patients/$patientId/billing": typeof DashboardPatientsPatientIdBillingRoute;
  "/dashboard/patients/$patientId/documents": typeof DashboardPatientsPatientIdDocumentsRouteWithChildren;
  "/dashboard/patients/$patientId/orders": typeof DashboardPatientsPatientIdOrdersRoute;
  "/dashboard/patients/$patientId/prescriptions": typeof DashboardPatientsPatientIdPrescriptionsRouteWithChildren;
  "/dashboard/patients/$patientId/timeline": typeof DashboardPatientsPatientIdTimelineRoute;
  "/dashboard/settings/clinic/branding": typeof DashboardSettingsClinicBrandingRoute;
  "/dashboard/settings/clinic/compliance": typeof DashboardSettingsClinicComplianceRoute;
  "/dashboard/settings/clinic/details": typeof DashboardSettingsClinicDetailsRoute;
  "/dashboard/settings/clinic/hours": typeof DashboardSettingsClinicHoursRoute;
  "/dashboard/settings/clinic/rooms": typeof DashboardSettingsClinicRoomsRoute;
  "/dashboard/patients/$patientId/": typeof DashboardPatientsPatientIdIndexRoute;
  "/dashboard/settings/clinic/": typeof DashboardSettingsClinicIndexRoute;
  "/dashboard/patients/$patientId/documents/new": typeof DashboardPatientsPatientIdDocumentsNewRoute;
  "/dashboard/patients/$patientId/invoices/$invoiceId": typeof DashboardPatientsPatientIdInvoicesInvoiceIdRoute;
  "/dashboard/patients/$patientId/invoices/new": typeof DashboardPatientsPatientIdInvoicesNewRoute;
  "/dashboard/patients/$patientId/prescriptions/new": typeof DashboardPatientsPatientIdPrescriptionsNewRoute;
  "/dashboard/settings/organization/clinics/new": typeof DashboardSettingsOrganizationClinicsNewRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/pricing": typeof PricingRoute;
  "/register": typeof RegisterRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/book/$slug": typeof BookSlugRoute;
  "/dashboard/audit-log": typeof DashboardAuditLogRoute;
  "/dashboard/chart-search": typeof DashboardChartSearchRoute;
  "/dashboard/notifications": typeof DashboardNotificationsRoute;
  "/dashboard/recalls": typeof DashboardRecallsRoute;
  "/dashboard/reminders": typeof DashboardRemindersRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/waiting-room": typeof DashboardWaitingRoomRoute;
  "/invitations/accept": typeof InvitationsAcceptRoute;
  "/nps/$token": typeof NpsTokenRoute;
  "/platform/flags": typeof PlatformFlagsRoute;
  "/platform/metrics": typeof PlatformMetricsRoute;
  "/referral-chart/$token": typeof ReferralChartTokenRoute;
  "/reminders/$token": typeof RemindersTokenRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/platform": typeof PlatformIndexRoute;
  "/dashboard/appointments/calendar": typeof DashboardAppointmentsCalendarRoute;
  "/dashboard/appointments/new": typeof DashboardAppointmentsNewRoute;
  "/dashboard/billing/claims": typeof DashboardBillingClaimsRouteWithChildren;
  "/dashboard/billing/eligibility": typeof DashboardBillingEligibilityRoute;
  "/dashboard/billing/invoices": typeof DashboardBillingInvoicesRoute;
  "/dashboard/billing/loa": typeof DashboardBillingLoaRoute;
  "/dashboard/documents/generate": typeof DashboardDocumentsGenerateRoute;
  "/dashboard/documents/templates": typeof DashboardDocumentsTemplatesRoute;
  "/dashboard/insights/audit-log": typeof DashboardInsightsAuditLogRoute;
  "/dashboard/insights/reports": typeof DashboardInsightsReportsRoute;
  "/dashboard/outreach/recalls": typeof DashboardOutreachRecallsRoute;
  "/dashboard/outreach/reminders": typeof DashboardOutreachRemindersRoute;
  "/dashboard/patients/chart-search": typeof DashboardPatientsChartSearchRoute;
  "/dashboard/patients/new": typeof DashboardPatientsNewRoute;
  "/dashboard/settings/account": typeof DashboardSettingsAccountRoute;
  "/dashboard/settings/assistant": typeof DashboardSettingsAssistantRoute;
  "/dashboard/settings/doctor": typeof DashboardSettingsDoctorRoute;
  "/dashboard/settings/document-templates": typeof DashboardSettingsDocumentTemplatesRoute;
  "/dashboard/settings/membership-plans": typeof DashboardSettingsMembershipPlansRoute;
  "/dashboard/settings/notifications": typeof DashboardSettingsNotificationsRoute;
  "/dashboard/settings/organization": typeof DashboardSettingsOrganizationRouteWithChildren;
  "/dashboard/settings/payers": typeof DashboardSettingsPayersRoute;
  "/dashboard/settings/plan": typeof DashboardSettingsPlanRoute;
  "/dashboard/settings/services": typeof DashboardSettingsServicesRoute;
  "/dashboard/settings/team": typeof DashboardSettingsTeamRoute;
  "/patient-portal/$slug/chart": typeof PatientPortalSlugChartRoute;
  "/patient-portal/$slug/documents": typeof PatientPortalSlugDocumentsRoute;
  "/patient-portal/$slug/invoices": typeof PatientPortalSlugInvoicesRoute;
  "/patient-portal/$slug/login": typeof PatientPortalSlugLoginRoute;
  "/patient-portal/$slug/verify": typeof PatientPortalSlugVerifyRoute;
  "/patient-portal/$slug/visits": typeof PatientPortalSlugVisitsRoute;
  "/platform/tenants/$clinicId": typeof PlatformTenantsClinicIdRoute;
  "/dashboard/appointments": typeof DashboardAppointmentsIndexRoute;
  "/dashboard/billing": typeof DashboardBillingIndexRoute;
  "/dashboard/documents": typeof DashboardDocumentsIndexRoute;
  "/dashboard/insights": typeof DashboardInsightsIndexRoute;
  "/dashboard/outreach": typeof DashboardOutreachIndexRoute;
  "/dashboard/patients": typeof DashboardPatientsIndexRoute;
  "/dashboard/settings": typeof DashboardSettingsIndexRoute;
  "/patient-portal/$slug": typeof PatientPortalSlugIndexRoute;
  "/dashboard/appointments/$appointmentId/soap": typeof DashboardAppointmentsAppointmentIdSoapRoute;
  "/dashboard/billing/claims/$claimId": typeof DashboardBillingClaimsClaimIdRoute;
  "/dashboard/patients/$patientId/activity": typeof DashboardPatientsPatientIdActivityRoute;
  "/dashboard/patients/$patientId/billing": typeof DashboardPatientsPatientIdBillingRoute;
  "/dashboard/patients/$patientId/documents": typeof DashboardPatientsPatientIdDocumentsRouteWithChildren;
  "/dashboard/patients/$patientId/orders": typeof DashboardPatientsPatientIdOrdersRoute;
  "/dashboard/patients/$patientId/prescriptions": typeof DashboardPatientsPatientIdPrescriptionsRouteWithChildren;
  "/dashboard/patients/$patientId/timeline": typeof DashboardPatientsPatientIdTimelineRoute;
  "/dashboard/settings/clinic/branding": typeof DashboardSettingsClinicBrandingRoute;
  "/dashboard/settings/clinic/compliance": typeof DashboardSettingsClinicComplianceRoute;
  "/dashboard/settings/clinic/details": typeof DashboardSettingsClinicDetailsRoute;
  "/dashboard/settings/clinic/hours": typeof DashboardSettingsClinicHoursRoute;
  "/dashboard/settings/clinic/rooms": typeof DashboardSettingsClinicRoomsRoute;
  "/dashboard/patients/$patientId": typeof DashboardPatientsPatientIdIndexRoute;
  "/dashboard/settings/clinic": typeof DashboardSettingsClinicIndexRoute;
  "/dashboard/patients/$patientId/documents/new": typeof DashboardPatientsPatientIdDocumentsNewRoute;
  "/dashboard/patients/$patientId/invoices/$invoiceId": typeof DashboardPatientsPatientIdInvoicesInvoiceIdRoute;
  "/dashboard/patients/$patientId/invoices/new": typeof DashboardPatientsPatientIdInvoicesNewRoute;
  "/dashboard/patients/$patientId/prescriptions/new": typeof DashboardPatientsPatientIdPrescriptionsNewRoute;
  "/dashboard/settings/organization/clinics/new": typeof DashboardSettingsOrganizationClinicsNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/platform": typeof PlatformRouteWithChildren;
  "/pricing": typeof PricingRoute;
  "/register": typeof RegisterRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/book/$slug": typeof BookSlugRoute;
  "/dashboard/appointments": typeof DashboardAppointmentsRouteWithChildren;
  "/dashboard/audit-log": typeof DashboardAuditLogRoute;
  "/dashboard/billing": typeof DashboardBillingRouteWithChildren;
  "/dashboard/chart-search": typeof DashboardChartSearchRoute;
  "/dashboard/documents": typeof DashboardDocumentsRouteWithChildren;
  "/dashboard/insights": typeof DashboardInsightsRouteWithChildren;
  "/dashboard/notifications": typeof DashboardNotificationsRoute;
  "/dashboard/outreach": typeof DashboardOutreachRouteWithChildren;
  "/dashboard/recalls": typeof DashboardRecallsRoute;
  "/dashboard/reminders": typeof DashboardRemindersRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRouteWithChildren;
  "/dashboard/waiting-room": typeof DashboardWaitingRoomRoute;
  "/invitations/accept": typeof InvitationsAcceptRoute;
  "/nps/$token": typeof NpsTokenRoute;
  "/platform/flags": typeof PlatformFlagsRoute;
  "/platform/metrics": typeof PlatformMetricsRoute;
  "/referral-chart/$token": typeof ReferralChartTokenRoute;
  "/reminders/$token": typeof RemindersTokenRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/platform/": typeof PlatformIndexRoute;
  "/dashboard/appointments/calendar": typeof DashboardAppointmentsCalendarRoute;
  "/dashboard/appointments/new": typeof DashboardAppointmentsNewRoute;
  "/dashboard/billing/claims": typeof DashboardBillingClaimsRouteWithChildren;
  "/dashboard/billing/eligibility": typeof DashboardBillingEligibilityRoute;
  "/dashboard/billing/invoices": typeof DashboardBillingInvoicesRoute;
  "/dashboard/billing/loa": typeof DashboardBillingLoaRoute;
  "/dashboard/documents/generate": typeof DashboardDocumentsGenerateRoute;
  "/dashboard/documents/templates": typeof DashboardDocumentsTemplatesRoute;
  "/dashboard/insights/audit-log": typeof DashboardInsightsAuditLogRoute;
  "/dashboard/insights/reports": typeof DashboardInsightsReportsRoute;
  "/dashboard/outreach/recalls": typeof DashboardOutreachRecallsRoute;
  "/dashboard/outreach/reminders": typeof DashboardOutreachRemindersRoute;
  "/dashboard/patients/$patientId": typeof DashboardPatientsPatientIdRouteWithChildren;
  "/dashboard/patients/chart-search": typeof DashboardPatientsChartSearchRoute;
  "/dashboard/patients/new": typeof DashboardPatientsNewRoute;
  "/dashboard/settings/account": typeof DashboardSettingsAccountRoute;
  "/dashboard/settings/assistant": typeof DashboardSettingsAssistantRoute;
  "/dashboard/settings/clinic": typeof DashboardSettingsClinicRouteWithChildren;
  "/dashboard/settings/doctor": typeof DashboardSettingsDoctorRoute;
  "/dashboard/settings/document-templates": typeof DashboardSettingsDocumentTemplatesRoute;
  "/dashboard/settings/membership-plans": typeof DashboardSettingsMembershipPlansRoute;
  "/dashboard/settings/notifications": typeof DashboardSettingsNotificationsRoute;
  "/dashboard/settings/organization": typeof DashboardSettingsOrganizationRouteWithChildren;
  "/dashboard/settings/payers": typeof DashboardSettingsPayersRoute;
  "/dashboard/settings/plan": typeof DashboardSettingsPlanRoute;
  "/dashboard/settings/services": typeof DashboardSettingsServicesRoute;
  "/dashboard/settings/team": typeof DashboardSettingsTeamRoute;
  "/patient-portal/$slug/chart": typeof PatientPortalSlugChartRoute;
  "/patient-portal/$slug/documents": typeof PatientPortalSlugDocumentsRoute;
  "/patient-portal/$slug/invoices": typeof PatientPortalSlugInvoicesRoute;
  "/patient-portal/$slug/login": typeof PatientPortalSlugLoginRoute;
  "/patient-portal/$slug/verify": typeof PatientPortalSlugVerifyRoute;
  "/patient-portal/$slug/visits": typeof PatientPortalSlugVisitsRoute;
  "/platform/tenants/$clinicId": typeof PlatformTenantsClinicIdRoute;
  "/dashboard/appointments/": typeof DashboardAppointmentsIndexRoute;
  "/dashboard/billing/": typeof DashboardBillingIndexRoute;
  "/dashboard/documents/": typeof DashboardDocumentsIndexRoute;
  "/dashboard/insights/": typeof DashboardInsightsIndexRoute;
  "/dashboard/outreach/": typeof DashboardOutreachIndexRoute;
  "/dashboard/patients/": typeof DashboardPatientsIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/patient-portal/$slug/": typeof PatientPortalSlugIndexRoute;
  "/dashboard/appointments/$appointmentId/soap": typeof DashboardAppointmentsAppointmentIdSoapRoute;
  "/dashboard/billing/claims/$claimId": typeof DashboardBillingClaimsClaimIdRoute;
  "/dashboard/patients/$patientId/activity": typeof DashboardPatientsPatientIdActivityRoute;
  "/dashboard/patients/$patientId/billing": typeof DashboardPatientsPatientIdBillingRoute;
  "/dashboard/patients/$patientId/documents": typeof DashboardPatientsPatientIdDocumentsRouteWithChildren;
  "/dashboard/patients/$patientId/orders": typeof DashboardPatientsPatientIdOrdersRoute;
  "/dashboard/patients/$patientId/prescriptions": typeof DashboardPatientsPatientIdPrescriptionsRouteWithChildren;
  "/dashboard/patients/$patientId/timeline": typeof DashboardPatientsPatientIdTimelineRoute;
  "/dashboard/settings/clinic/branding": typeof DashboardSettingsClinicBrandingRoute;
  "/dashboard/settings/clinic/compliance": typeof DashboardSettingsClinicComplianceRoute;
  "/dashboard/settings/clinic/details": typeof DashboardSettingsClinicDetailsRoute;
  "/dashboard/settings/clinic/hours": typeof DashboardSettingsClinicHoursRoute;
  "/dashboard/settings/clinic/rooms": typeof DashboardSettingsClinicRoomsRoute;
  "/dashboard/patients/$patientId/": typeof DashboardPatientsPatientIdIndexRoute;
  "/dashboard/settings/clinic/": typeof DashboardSettingsClinicIndexRoute;
  "/dashboard/patients/$patientId/documents/new": typeof DashboardPatientsPatientIdDocumentsNewRoute;
  "/dashboard/patients/$patientId/invoices/$invoiceId": typeof DashboardPatientsPatientIdInvoicesInvoiceIdRoute;
  "/dashboard/patients/$patientId/invoices/new": typeof DashboardPatientsPatientIdInvoicesNewRoute;
  "/dashboard/patients/$patientId/prescriptions/new": typeof DashboardPatientsPatientIdPrescriptionsNewRoute;
  "/dashboard/settings/organization/clinics/new": typeof DashboardSettingsOrganizationClinicsNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/platform"
    | "/pricing"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/book/$slug"
    | "/dashboard/appointments"
    | "/dashboard/audit-log"
    | "/dashboard/billing"
    | "/dashboard/chart-search"
    | "/dashboard/documents"
    | "/dashboard/insights"
    | "/dashboard/notifications"
    | "/dashboard/outreach"
    | "/dashboard/recalls"
    | "/dashboard/reminders"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard/waiting-room"
    | "/invitations/accept"
    | "/nps/$token"
    | "/platform/flags"
    | "/platform/metrics"
    | "/referral-chart/$token"
    | "/reminders/$token"
    | "/dashboard/"
    | "/platform/"
    | "/dashboard/appointments/calendar"
    | "/dashboard/appointments/new"
    | "/dashboard/billing/claims"
    | "/dashboard/billing/eligibility"
    | "/dashboard/billing/invoices"
    | "/dashboard/billing/loa"
    | "/dashboard/documents/generate"
    | "/dashboard/documents/templates"
    | "/dashboard/insights/audit-log"
    | "/dashboard/insights/reports"
    | "/dashboard/outreach/recalls"
    | "/dashboard/outreach/reminders"
    | "/dashboard/patients/$patientId"
    | "/dashboard/patients/chart-search"
    | "/dashboard/patients/new"
    | "/dashboard/settings/account"
    | "/dashboard/settings/assistant"
    | "/dashboard/settings/clinic"
    | "/dashboard/settings/doctor"
    | "/dashboard/settings/document-templates"
    | "/dashboard/settings/membership-plans"
    | "/dashboard/settings/notifications"
    | "/dashboard/settings/organization"
    | "/dashboard/settings/payers"
    | "/dashboard/settings/plan"
    | "/dashboard/settings/services"
    | "/dashboard/settings/team"
    | "/patient-portal/$slug/chart"
    | "/patient-portal/$slug/documents"
    | "/patient-portal/$slug/invoices"
    | "/patient-portal/$slug/login"
    | "/patient-portal/$slug/verify"
    | "/patient-portal/$slug/visits"
    | "/platform/tenants/$clinicId"
    | "/dashboard/appointments/"
    | "/dashboard/billing/"
    | "/dashboard/documents/"
    | "/dashboard/insights/"
    | "/dashboard/outreach/"
    | "/dashboard/patients/"
    | "/dashboard/settings/"
    | "/patient-portal/$slug/"
    | "/dashboard/appointments/$appointmentId/soap"
    | "/dashboard/billing/claims/$claimId"
    | "/dashboard/patients/$patientId/activity"
    | "/dashboard/patients/$patientId/billing"
    | "/dashboard/patients/$patientId/documents"
    | "/dashboard/patients/$patientId/orders"
    | "/dashboard/patients/$patientId/prescriptions"
    | "/dashboard/patients/$patientId/timeline"
    | "/dashboard/settings/clinic/branding"
    | "/dashboard/settings/clinic/compliance"
    | "/dashboard/settings/clinic/details"
    | "/dashboard/settings/clinic/hours"
    | "/dashboard/settings/clinic/rooms"
    | "/dashboard/patients/$patientId/"
    | "/dashboard/settings/clinic/"
    | "/dashboard/patients/$patientId/documents/new"
    | "/dashboard/patients/$patientId/invoices/$invoiceId"
    | "/dashboard/patients/$patientId/invoices/new"
    | "/dashboard/patients/$patientId/prescriptions/new"
    | "/dashboard/settings/organization/clinics/new";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/pricing"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/book/$slug"
    | "/dashboard/audit-log"
    | "/dashboard/chart-search"
    | "/dashboard/notifications"
    | "/dashboard/recalls"
    | "/dashboard/reminders"
    | "/dashboard/reports"
    | "/dashboard/waiting-room"
    | "/invitations/accept"
    | "/nps/$token"
    | "/platform/flags"
    | "/platform/metrics"
    | "/referral-chart/$token"
    | "/reminders/$token"
    | "/dashboard"
    | "/platform"
    | "/dashboard/appointments/calendar"
    | "/dashboard/appointments/new"
    | "/dashboard/billing/claims"
    | "/dashboard/billing/eligibility"
    | "/dashboard/billing/invoices"
    | "/dashboard/billing/loa"
    | "/dashboard/documents/generate"
    | "/dashboard/documents/templates"
    | "/dashboard/insights/audit-log"
    | "/dashboard/insights/reports"
    | "/dashboard/outreach/recalls"
    | "/dashboard/outreach/reminders"
    | "/dashboard/patients/chart-search"
    | "/dashboard/patients/new"
    | "/dashboard/settings/account"
    | "/dashboard/settings/assistant"
    | "/dashboard/settings/doctor"
    | "/dashboard/settings/document-templates"
    | "/dashboard/settings/membership-plans"
    | "/dashboard/settings/notifications"
    | "/dashboard/settings/organization"
    | "/dashboard/settings/payers"
    | "/dashboard/settings/plan"
    | "/dashboard/settings/services"
    | "/dashboard/settings/team"
    | "/patient-portal/$slug/chart"
    | "/patient-portal/$slug/documents"
    | "/patient-portal/$slug/invoices"
    | "/patient-portal/$slug/login"
    | "/patient-portal/$slug/verify"
    | "/patient-portal/$slug/visits"
    | "/platform/tenants/$clinicId"
    | "/dashboard/appointments"
    | "/dashboard/billing"
    | "/dashboard/documents"
    | "/dashboard/insights"
    | "/dashboard/outreach"
    | "/dashboard/patients"
    | "/dashboard/settings"
    | "/patient-portal/$slug"
    | "/dashboard/appointments/$appointmentId/soap"
    | "/dashboard/billing/claims/$claimId"
    | "/dashboard/patients/$patientId/activity"
    | "/dashboard/patients/$patientId/billing"
    | "/dashboard/patients/$patientId/documents"
    | "/dashboard/patients/$patientId/orders"
    | "/dashboard/patients/$patientId/prescriptions"
    | "/dashboard/patients/$patientId/timeline"
    | "/dashboard/settings/clinic/branding"
    | "/dashboard/settings/clinic/compliance"
    | "/dashboard/settings/clinic/details"
    | "/dashboard/settings/clinic/hours"
    | "/dashboard/settings/clinic/rooms"
    | "/dashboard/patients/$patientId"
    | "/dashboard/settings/clinic"
    | "/dashboard/patients/$patientId/documents/new"
    | "/dashboard/patients/$patientId/invoices/$invoiceId"
    | "/dashboard/patients/$patientId/invoices/new"
    | "/dashboard/patients/$patientId/prescriptions/new"
    | "/dashboard/settings/organization/clinics/new";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/platform"
    | "/pricing"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/book/$slug"
    | "/dashboard/appointments"
    | "/dashboard/audit-log"
    | "/dashboard/billing"
    | "/dashboard/chart-search"
    | "/dashboard/documents"
    | "/dashboard/insights"
    | "/dashboard/notifications"
    | "/dashboard/outreach"
    | "/dashboard/recalls"
    | "/dashboard/reminders"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard/waiting-room"
    | "/invitations/accept"
    | "/nps/$token"
    | "/platform/flags"
    | "/platform/metrics"
    | "/referral-chart/$token"
    | "/reminders/$token"
    | "/dashboard/"
    | "/platform/"
    | "/dashboard/appointments/calendar"
    | "/dashboard/appointments/new"
    | "/dashboard/billing/claims"
    | "/dashboard/billing/eligibility"
    | "/dashboard/billing/invoices"
    | "/dashboard/billing/loa"
    | "/dashboard/documents/generate"
    | "/dashboard/documents/templates"
    | "/dashboard/insights/audit-log"
    | "/dashboard/insights/reports"
    | "/dashboard/outreach/recalls"
    | "/dashboard/outreach/reminders"
    | "/dashboard/patients/$patientId"
    | "/dashboard/patients/chart-search"
    | "/dashboard/patients/new"
    | "/dashboard/settings/account"
    | "/dashboard/settings/assistant"
    | "/dashboard/settings/clinic"
    | "/dashboard/settings/doctor"
    | "/dashboard/settings/document-templates"
    | "/dashboard/settings/membership-plans"
    | "/dashboard/settings/notifications"
    | "/dashboard/settings/organization"
    | "/dashboard/settings/payers"
    | "/dashboard/settings/plan"
    | "/dashboard/settings/services"
    | "/dashboard/settings/team"
    | "/patient-portal/$slug/chart"
    | "/patient-portal/$slug/documents"
    | "/patient-portal/$slug/invoices"
    | "/patient-portal/$slug/login"
    | "/patient-portal/$slug/verify"
    | "/patient-portal/$slug/visits"
    | "/platform/tenants/$clinicId"
    | "/dashboard/appointments/"
    | "/dashboard/billing/"
    | "/dashboard/documents/"
    | "/dashboard/insights/"
    | "/dashboard/outreach/"
    | "/dashboard/patients/"
    | "/dashboard/settings/"
    | "/patient-portal/$slug/"
    | "/dashboard/appointments/$appointmentId/soap"
    | "/dashboard/billing/claims/$claimId"
    | "/dashboard/patients/$patientId/activity"
    | "/dashboard/patients/$patientId/billing"
    | "/dashboard/patients/$patientId/documents"
    | "/dashboard/patients/$patientId/orders"
    | "/dashboard/patients/$patientId/prescriptions"
    | "/dashboard/patients/$patientId/timeline"
    | "/dashboard/settings/clinic/branding"
    | "/dashboard/settings/clinic/compliance"
    | "/dashboard/settings/clinic/details"
    | "/dashboard/settings/clinic/hours"
    | "/dashboard/settings/clinic/rooms"
    | "/dashboard/patients/$patientId/"
    | "/dashboard/settings/clinic/"
    | "/dashboard/patients/$patientId/documents/new"
    | "/dashboard/patients/$patientId/invoices/$invoiceId"
    | "/dashboard/patients/$patientId/invoices/new"
    | "/dashboard/patients/$patientId/prescriptions/new"
    | "/dashboard/settings/organization/clinics/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  PlatformRoute: typeof PlatformRouteWithChildren;
  PricingRoute: typeof PricingRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  VerifyEmailRoute: typeof VerifyEmailRoute;
  BookSlugRoute: typeof BookSlugRoute;
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute;
  NpsTokenRoute: typeof NpsTokenRoute;
  ReferralChartTokenRoute: typeof ReferralChartTokenRoute;
  RemindersTokenRoute: typeof RemindersTokenRoute;
  PatientPortalSlugChartRoute: typeof PatientPortalSlugChartRoute;
  PatientPortalSlugDocumentsRoute: typeof PatientPortalSlugDocumentsRoute;
  PatientPortalSlugInvoicesRoute: typeof PatientPortalSlugInvoicesRoute;
  PatientPortalSlugLoginRoute: typeof PatientPortalSlugLoginRoute;
  PatientPortalSlugVerifyRoute: typeof PatientPortalSlugVerifyRoute;
  PatientPortalSlugVisitsRoute: typeof PatientPortalSlugVisitsRoute;
  PatientPortalSlugIndexRoute: typeof PatientPortalSlugIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/platform": {
      id: "/platform";
      path: "/platform";
      fullPath: "/platform";
      preLoaderRoute: typeof PlatformRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pricing": {
      id: "/pricing";
      path: "/pricing";
      fullPath: "/pricing";
      preLoaderRoute: typeof PricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reset-password": {
      id: "/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/verify-email": {
      id: "/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof VerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/book/$slug": {
      id: "/book/$slug";
      path: "/book/$slug";
      fullPath: "/book/$slug";
      preLoaderRoute: typeof BookSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/appointments": {
      id: "/dashboard/appointments";
      path: "/appointments";
      fullPath: "/dashboard/appointments";
      preLoaderRoute: typeof DashboardAppointmentsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/audit-log": {
      id: "/dashboard/audit-log";
      path: "/audit-log";
      fullPath: "/dashboard/audit-log";
      preLoaderRoute: typeof DashboardAuditLogRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/billing": {
      id: "/dashboard/billing";
      path: "/billing";
      fullPath: "/dashboard/billing";
      preLoaderRoute: typeof DashboardBillingRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/chart-search": {
      id: "/dashboard/chart-search";
      path: "/chart-search";
      fullPath: "/dashboard/chart-search";
      preLoaderRoute: typeof DashboardChartSearchRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/documents": {
      id: "/dashboard/documents";
      path: "/documents";
      fullPath: "/dashboard/documents";
      preLoaderRoute: typeof DashboardDocumentsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/insights": {
      id: "/dashboard/insights";
      path: "/insights";
      fullPath: "/dashboard/insights";
      preLoaderRoute: typeof DashboardInsightsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/notifications": {
      id: "/dashboard/notifications";
      path: "/notifications";
      fullPath: "/dashboard/notifications";
      preLoaderRoute: typeof DashboardNotificationsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/outreach": {
      id: "/dashboard/outreach";
      path: "/outreach";
      fullPath: "/dashboard/outreach";
      preLoaderRoute: typeof DashboardOutreachRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/recalls": {
      id: "/dashboard/recalls";
      path: "/recalls";
      fullPath: "/dashboard/recalls";
      preLoaderRoute: typeof DashboardRecallsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/reminders": {
      id: "/dashboard/reminders";
      path: "/reminders";
      fullPath: "/dashboard/reminders";
      preLoaderRoute: typeof DashboardRemindersRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/reports": {
      id: "/dashboard/reports";
      path: "/reports";
      fullPath: "/dashboard/reports";
      preLoaderRoute: typeof DashboardReportsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/waiting-room": {
      id: "/dashboard/waiting-room";
      path: "/waiting-room";
      fullPath: "/dashboard/waiting-room";
      preLoaderRoute: typeof DashboardWaitingRoomRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/invitations/accept": {
      id: "/invitations/accept";
      path: "/invitations/accept";
      fullPath: "/invitations/accept";
      preLoaderRoute: typeof InvitationsAcceptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/nps/$token": {
      id: "/nps/$token";
      path: "/nps/$token";
      fullPath: "/nps/$token";
      preLoaderRoute: typeof NpsTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/platform/": {
      id: "/platform/";
      path: "/";
      fullPath: "/platform/";
      preLoaderRoute: typeof PlatformIndexRouteImport;
      parentRoute: typeof PlatformRoute;
    };
    "/platform/flags": {
      id: "/platform/flags";
      path: "/flags";
      fullPath: "/platform/flags";
      preLoaderRoute: typeof PlatformFlagsRouteImport;
      parentRoute: typeof PlatformRoute;
    };
    "/platform/metrics": {
      id: "/platform/metrics";
      path: "/metrics";
      fullPath: "/platform/metrics";
      preLoaderRoute: typeof PlatformMetricsRouteImport;
      parentRoute: typeof PlatformRoute;
    };
    "/referral-chart/$token": {
      id: "/referral-chart/$token";
      path: "/referral-chart/$token";
      fullPath: "/referral-chart/$token";
      preLoaderRoute: typeof ReferralChartTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders/$token": {
      id: "/reminders/$token";
      path: "/reminders/$token";
      fullPath: "/reminders/$token";
      preLoaderRoute: typeof RemindersTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/appointments/": {
      id: "/dashboard/appointments/";
      path: "/";
      fullPath: "/dashboard/appointments/";
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport;
      parentRoute: typeof DashboardAppointmentsRoute;
    };
    "/dashboard/appointments/calendar": {
      id: "/dashboard/appointments/calendar";
      path: "/calendar";
      fullPath: "/dashboard/appointments/calendar";
      preLoaderRoute: typeof DashboardAppointmentsCalendarRouteImport;
      parentRoute: typeof DashboardAppointmentsRoute;
    };
    "/dashboard/appointments/new": {
      id: "/dashboard/appointments/new";
      path: "/new";
      fullPath: "/dashboard/appointments/new";
      preLoaderRoute: typeof DashboardAppointmentsNewRouteImport;
      parentRoute: typeof DashboardAppointmentsRoute;
    };
    "/dashboard/billing/": {
      id: "/dashboard/billing/";
      path: "/";
      fullPath: "/dashboard/billing/";
      preLoaderRoute: typeof DashboardBillingIndexRouteImport;
      parentRoute: typeof DashboardBillingRoute;
    };
    "/dashboard/billing/claims": {
      id: "/dashboard/billing/claims";
      path: "/claims";
      fullPath: "/dashboard/billing/claims";
      preLoaderRoute: typeof DashboardBillingClaimsRouteImport;
      parentRoute: typeof DashboardBillingRoute;
    };
    "/dashboard/billing/eligibility": {
      id: "/dashboard/billing/eligibility";
      path: "/eligibility";
      fullPath: "/dashboard/billing/eligibility";
      preLoaderRoute: typeof DashboardBillingEligibilityRouteImport;
      parentRoute: typeof DashboardBillingRoute;
    };
    "/dashboard/billing/invoices": {
      id: "/dashboard/billing/invoices";
      path: "/invoices";
      fullPath: "/dashboard/billing/invoices";
      preLoaderRoute: typeof DashboardBillingInvoicesRouteImport;
      parentRoute: typeof DashboardBillingRoute;
    };
    "/dashboard/billing/loa": {
      id: "/dashboard/billing/loa";
      path: "/loa";
      fullPath: "/dashboard/billing/loa";
      preLoaderRoute: typeof DashboardBillingLoaRouteImport;
      parentRoute: typeof DashboardBillingRoute;
    };
    "/dashboard/documents/": {
      id: "/dashboard/documents/";
      path: "/";
      fullPath: "/dashboard/documents/";
      preLoaderRoute: typeof DashboardDocumentsIndexRouteImport;
      parentRoute: typeof DashboardDocumentsRoute;
    };
    "/dashboard/documents/generate": {
      id: "/dashboard/documents/generate";
      path: "/generate";
      fullPath: "/dashboard/documents/generate";
      preLoaderRoute: typeof DashboardDocumentsGenerateRouteImport;
      parentRoute: typeof DashboardDocumentsRoute;
    };
    "/dashboard/documents/templates": {
      id: "/dashboard/documents/templates";
      path: "/templates";
      fullPath: "/dashboard/documents/templates";
      preLoaderRoute: typeof DashboardDocumentsTemplatesRouteImport;
      parentRoute: typeof DashboardDocumentsRoute;
    };
    "/dashboard/insights/": {
      id: "/dashboard/insights/";
      path: "/";
      fullPath: "/dashboard/insights/";
      preLoaderRoute: typeof DashboardInsightsIndexRouteImport;
      parentRoute: typeof DashboardInsightsRoute;
    };
    "/dashboard/insights/audit-log": {
      id: "/dashboard/insights/audit-log";
      path: "/audit-log";
      fullPath: "/dashboard/insights/audit-log";
      preLoaderRoute: typeof DashboardInsightsAuditLogRouteImport;
      parentRoute: typeof DashboardInsightsRoute;
    };
    "/dashboard/insights/reports": {
      id: "/dashboard/insights/reports";
      path: "/reports";
      fullPath: "/dashboard/insights/reports";
      preLoaderRoute: typeof DashboardInsightsReportsRouteImport;
      parentRoute: typeof DashboardInsightsRoute;
    };
    "/dashboard/outreach/": {
      id: "/dashboard/outreach/";
      path: "/";
      fullPath: "/dashboard/outreach/";
      preLoaderRoute: typeof DashboardOutreachIndexRouteImport;
      parentRoute: typeof DashboardOutreachRoute;
    };
    "/dashboard/outreach/recalls": {
      id: "/dashboard/outreach/recalls";
      path: "/recalls";
      fullPath: "/dashboard/outreach/recalls";
      preLoaderRoute: typeof DashboardOutreachRecallsRouteImport;
      parentRoute: typeof DashboardOutreachRoute;
    };
    "/dashboard/outreach/reminders": {
      id: "/dashboard/outreach/reminders";
      path: "/reminders";
      fullPath: "/dashboard/outreach/reminders";
      preLoaderRoute: typeof DashboardOutreachRemindersRouteImport;
      parentRoute: typeof DashboardOutreachRoute;
    };
    "/dashboard/patients/": {
      id: "/dashboard/patients/";
      path: "/patients";
      fullPath: "/dashboard/patients/";
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/patients/$patientId": {
      id: "/dashboard/patients/$patientId";
      path: "/patients/$patientId";
      fullPath: "/dashboard/patients/$patientId";
      preLoaderRoute: typeof DashboardPatientsPatientIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/patients/chart-search": {
      id: "/dashboard/patients/chart-search";
      path: "/patients/chart-search";
      fullPath: "/dashboard/patients/chart-search";
      preLoaderRoute: typeof DashboardPatientsChartSearchRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/patients/new": {
      id: "/dashboard/patients/new";
      path: "/patients/new";
      fullPath: "/dashboard/patients/new";
      preLoaderRoute: typeof DashboardPatientsNewRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/settings/": {
      id: "/dashboard/settings/";
      path: "/";
      fullPath: "/dashboard/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/account": {
      id: "/dashboard/settings/account";
      path: "/account";
      fullPath: "/dashboard/settings/account";
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/assistant": {
      id: "/dashboard/settings/assistant";
      path: "/assistant";
      fullPath: "/dashboard/settings/assistant";
      preLoaderRoute: typeof DashboardSettingsAssistantRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/clinic": {
      id: "/dashboard/settings/clinic";
      path: "/clinic";
      fullPath: "/dashboard/settings/clinic";
      preLoaderRoute: typeof DashboardSettingsClinicRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/doctor": {
      id: "/dashboard/settings/doctor";
      path: "/doctor";
      fullPath: "/dashboard/settings/doctor";
      preLoaderRoute: typeof DashboardSettingsDoctorRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/document-templates": {
      id: "/dashboard/settings/document-templates";
      path: "/document-templates";
      fullPath: "/dashboard/settings/document-templates";
      preLoaderRoute: typeof DashboardSettingsDocumentTemplatesRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/membership-plans": {
      id: "/dashboard/settings/membership-plans";
      path: "/membership-plans";
      fullPath: "/dashboard/settings/membership-plans";
      preLoaderRoute: typeof DashboardSettingsMembershipPlansRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/notifications": {
      id: "/dashboard/settings/notifications";
      path: "/notifications";
      fullPath: "/dashboard/settings/notifications";
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/organization": {
      id: "/dashboard/settings/organization";
      path: "/organization";
      fullPath: "/dashboard/settings/organization";
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/payers": {
      id: "/dashboard/settings/payers";
      path: "/payers";
      fullPath: "/dashboard/settings/payers";
      preLoaderRoute: typeof DashboardSettingsPayersRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/plan": {
      id: "/dashboard/settings/plan";
      path: "/plan";
      fullPath: "/dashboard/settings/plan";
      preLoaderRoute: typeof DashboardSettingsPlanRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/services": {
      id: "/dashboard/settings/services";
      path: "/services";
      fullPath: "/dashboard/settings/services";
      preLoaderRoute: typeof DashboardSettingsServicesRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/dashboard/settings/team": {
      id: "/dashboard/settings/team";
      path: "/team";
      fullPath: "/dashboard/settings/team";
      preLoaderRoute: typeof DashboardSettingsTeamRouteImport;
      parentRoute: typeof DashboardSettingsRoute;
    };
    "/patient-portal/$slug/": {
      id: "/patient-portal/$slug/";
      path: "/patient-portal/$slug";
      fullPath: "/patient-portal/$slug/";
      preLoaderRoute: typeof PatientPortalSlugIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/patient-portal/$slug/chart": {
      id: "/patient-portal/$slug/chart";
      path: "/patient-portal/$slug/chart";
      fullPath: "/patient-portal/$slug/chart";
      preLoaderRoute: typeof PatientPortalSlugChartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/patient-portal/$slug/documents": {
      id: "/patient-portal/$slug/documents";
      path: "/patient-portal/$slug/documents";
      fullPath: "/patient-portal/$slug/documents";
      preLoaderRoute: typeof PatientPortalSlugDocumentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/patient-portal/$slug/invoices": {
      id: "/patient-portal/$slug/invoices";
      path: "/patient-portal/$slug/invoices";
      fullPath: "/patient-portal/$slug/invoices";
      preLoaderRoute: typeof PatientPortalSlugInvoicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/patient-portal/$slug/login": {
      id: "/patient-portal/$slug/login";
      path: "/patient-portal/$slug/login";
      fullPath: "/patient-portal/$slug/login";
      preLoaderRoute: typeof PatientPortalSlugLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/patient-portal/$slug/verify": {
      id: "/patient-portal/$slug/verify";
      path: "/patient-portal/$slug/verify";
      fullPath: "/patient-portal/$slug/verify";
      preLoaderRoute: typeof PatientPortalSlugVerifyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/patient-portal/$slug/visits": {
      id: "/patient-portal/$slug/visits";
      path: "/patient-portal/$slug/visits";
      fullPath: "/patient-portal/$slug/visits";
      preLoaderRoute: typeof PatientPortalSlugVisitsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/platform/tenants/$clinicId": {
      id: "/platform/tenants/$clinicId";
      path: "/tenants/$clinicId";
      fullPath: "/platform/tenants/$clinicId";
      preLoaderRoute: typeof PlatformTenantsClinicIdRouteImport;
      parentRoute: typeof PlatformRoute;
    };
    "/dashboard/appointments/$appointmentId/soap": {
      id: "/dashboard/appointments/$appointmentId/soap";
      path: "/$appointmentId/soap";
      fullPath: "/dashboard/appointments/$appointmentId/soap";
      preLoaderRoute: typeof DashboardAppointmentsAppointmentIdSoapRouteImport;
      parentRoute: typeof DashboardAppointmentsRoute;
    };
    "/dashboard/billing/claims/$claimId": {
      id: "/dashboard/billing/claims/$claimId";
      path: "/$claimId";
      fullPath: "/dashboard/billing/claims/$claimId";
      preLoaderRoute: typeof DashboardBillingClaimsClaimIdRouteImport;
      parentRoute: typeof DashboardBillingClaimsRoute;
    };
    "/dashboard/patients/$patientId/": {
      id: "/dashboard/patients/$patientId/";
      path: "/";
      fullPath: "/dashboard/patients/$patientId/";
      preLoaderRoute: typeof DashboardPatientsPatientIdIndexRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/activity": {
      id: "/dashboard/patients/$patientId/activity";
      path: "/activity";
      fullPath: "/dashboard/patients/$patientId/activity";
      preLoaderRoute: typeof DashboardPatientsPatientIdActivityRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/billing": {
      id: "/dashboard/patients/$patientId/billing";
      path: "/billing";
      fullPath: "/dashboard/patients/$patientId/billing";
      preLoaderRoute: typeof DashboardPatientsPatientIdBillingRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/documents": {
      id: "/dashboard/patients/$patientId/documents";
      path: "/documents";
      fullPath: "/dashboard/patients/$patientId/documents";
      preLoaderRoute: typeof DashboardPatientsPatientIdDocumentsRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/orders": {
      id: "/dashboard/patients/$patientId/orders";
      path: "/orders";
      fullPath: "/dashboard/patients/$patientId/orders";
      preLoaderRoute: typeof DashboardPatientsPatientIdOrdersRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/prescriptions": {
      id: "/dashboard/patients/$patientId/prescriptions";
      path: "/prescriptions";
      fullPath: "/dashboard/patients/$patientId/prescriptions";
      preLoaderRoute: typeof DashboardPatientsPatientIdPrescriptionsRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/timeline": {
      id: "/dashboard/patients/$patientId/timeline";
      path: "/timeline";
      fullPath: "/dashboard/patients/$patientId/timeline";
      preLoaderRoute: typeof DashboardPatientsPatientIdTimelineRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/settings/clinic/": {
      id: "/dashboard/settings/clinic/";
      path: "/";
      fullPath: "/dashboard/settings/clinic/";
      preLoaderRoute: typeof DashboardSettingsClinicIndexRouteImport;
      parentRoute: typeof DashboardSettingsClinicRoute;
    };
    "/dashboard/settings/clinic/branding": {
      id: "/dashboard/settings/clinic/branding";
      path: "/branding";
      fullPath: "/dashboard/settings/clinic/branding";
      preLoaderRoute: typeof DashboardSettingsClinicBrandingRouteImport;
      parentRoute: typeof DashboardSettingsClinicRoute;
    };
    "/dashboard/settings/clinic/compliance": {
      id: "/dashboard/settings/clinic/compliance";
      path: "/compliance";
      fullPath: "/dashboard/settings/clinic/compliance";
      preLoaderRoute: typeof DashboardSettingsClinicComplianceRouteImport;
      parentRoute: typeof DashboardSettingsClinicRoute;
    };
    "/dashboard/settings/clinic/details": {
      id: "/dashboard/settings/clinic/details";
      path: "/details";
      fullPath: "/dashboard/settings/clinic/details";
      preLoaderRoute: typeof DashboardSettingsClinicDetailsRouteImport;
      parentRoute: typeof DashboardSettingsClinicRoute;
    };
    "/dashboard/settings/clinic/hours": {
      id: "/dashboard/settings/clinic/hours";
      path: "/hours";
      fullPath: "/dashboard/settings/clinic/hours";
      preLoaderRoute: typeof DashboardSettingsClinicHoursRouteImport;
      parentRoute: typeof DashboardSettingsClinicRoute;
    };
    "/dashboard/settings/clinic/rooms": {
      id: "/dashboard/settings/clinic/rooms";
      path: "/rooms";
      fullPath: "/dashboard/settings/clinic/rooms";
      preLoaderRoute: typeof DashboardSettingsClinicRoomsRouteImport;
      parentRoute: typeof DashboardSettingsClinicRoute;
    };
    "/dashboard/patients/$patientId/documents/new": {
      id: "/dashboard/patients/$patientId/documents/new";
      path: "/new";
      fullPath: "/dashboard/patients/$patientId/documents/new";
      preLoaderRoute: typeof DashboardPatientsPatientIdDocumentsNewRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdDocumentsRoute;
    };
    "/dashboard/patients/$patientId/invoices/$invoiceId": {
      id: "/dashboard/patients/$patientId/invoices/$invoiceId";
      path: "/invoices/$invoiceId";
      fullPath: "/dashboard/patients/$patientId/invoices/$invoiceId";
      preLoaderRoute: typeof DashboardPatientsPatientIdInvoicesInvoiceIdRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/invoices/new": {
      id: "/dashboard/patients/$patientId/invoices/new";
      path: "/invoices/new";
      fullPath: "/dashboard/patients/$patientId/invoices/new";
      preLoaderRoute: typeof DashboardPatientsPatientIdInvoicesNewRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdRoute;
    };
    "/dashboard/patients/$patientId/prescriptions/new": {
      id: "/dashboard/patients/$patientId/prescriptions/new";
      path: "/new";
      fullPath: "/dashboard/patients/$patientId/prescriptions/new";
      preLoaderRoute: typeof DashboardPatientsPatientIdPrescriptionsNewRouteImport;
      parentRoute: typeof DashboardPatientsPatientIdPrescriptionsRoute;
    };
    "/dashboard/settings/organization/clinics/new": {
      id: "/dashboard/settings/organization/clinics/new";
      path: "/clinics/new";
      fullPath: "/dashboard/settings/organization/clinics/new";
      preLoaderRoute: typeof DashboardSettingsOrganizationClinicsNewRouteImport;
      parentRoute: typeof DashboardSettingsOrganizationRoute;
    };
  }
}

interface DashboardAppointmentsRouteChildren {
  DashboardAppointmentsCalendarRoute: typeof DashboardAppointmentsCalendarRoute;
  DashboardAppointmentsNewRoute: typeof DashboardAppointmentsNewRoute;
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute;
  DashboardAppointmentsAppointmentIdSoapRoute: typeof DashboardAppointmentsAppointmentIdSoapRoute;
}

const DashboardAppointmentsRouteChildren: DashboardAppointmentsRouteChildren = {
  DashboardAppointmentsCalendarRoute: DashboardAppointmentsCalendarRoute,
  DashboardAppointmentsNewRoute: DashboardAppointmentsNewRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardAppointmentsAppointmentIdSoapRoute:
    DashboardAppointmentsAppointmentIdSoapRoute,
};

const DashboardAppointmentsRouteWithChildren =
  DashboardAppointmentsRoute._addFileChildren(
    DashboardAppointmentsRouteChildren,
  );

interface DashboardBillingClaimsRouteChildren {
  DashboardBillingClaimsClaimIdRoute: typeof DashboardBillingClaimsClaimIdRoute;
}

const DashboardBillingClaimsRouteChildren: DashboardBillingClaimsRouteChildren =
  {
    DashboardBillingClaimsClaimIdRoute: DashboardBillingClaimsClaimIdRoute,
  };

const DashboardBillingClaimsRouteWithChildren =
  DashboardBillingClaimsRoute._addFileChildren(
    DashboardBillingClaimsRouteChildren,
  );

interface DashboardBillingRouteChildren {
  DashboardBillingClaimsRoute: typeof DashboardBillingClaimsRouteWithChildren;
  DashboardBillingEligibilityRoute: typeof DashboardBillingEligibilityRoute;
  DashboardBillingInvoicesRoute: typeof DashboardBillingInvoicesRoute;
  DashboardBillingLoaRoute: typeof DashboardBillingLoaRoute;
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute;
}

const DashboardBillingRouteChildren: DashboardBillingRouteChildren = {
  DashboardBillingClaimsRoute: DashboardBillingClaimsRouteWithChildren,
  DashboardBillingEligibilityRoute: DashboardBillingEligibilityRoute,
  DashboardBillingInvoicesRoute: DashboardBillingInvoicesRoute,
  DashboardBillingLoaRoute: DashboardBillingLoaRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
};

const DashboardBillingRouteWithChildren =
  DashboardBillingRoute._addFileChildren(DashboardBillingRouteChildren);

interface DashboardDocumentsRouteChildren {
  DashboardDocumentsGenerateRoute: typeof DashboardDocumentsGenerateRoute;
  DashboardDocumentsTemplatesRoute: typeof DashboardDocumentsTemplatesRoute;
  DashboardDocumentsIndexRoute: typeof DashboardDocumentsIndexRoute;
}

const DashboardDocumentsRouteChildren: DashboardDocumentsRouteChildren = {
  DashboardDocumentsGenerateRoute: DashboardDocumentsGenerateRoute,
  DashboardDocumentsTemplatesRoute: DashboardDocumentsTemplatesRoute,
  DashboardDocumentsIndexRoute: DashboardDocumentsIndexRoute,
};

const DashboardDocumentsRouteWithChildren =
  DashboardDocumentsRoute._addFileChildren(DashboardDocumentsRouteChildren);

interface DashboardInsightsRouteChildren {
  DashboardInsightsAuditLogRoute: typeof DashboardInsightsAuditLogRoute;
  DashboardInsightsReportsRoute: typeof DashboardInsightsReportsRoute;
  DashboardInsightsIndexRoute: typeof DashboardInsightsIndexRoute;
}

const DashboardInsightsRouteChildren: DashboardInsightsRouteChildren = {
  DashboardInsightsAuditLogRoute: DashboardInsightsAuditLogRoute,
  DashboardInsightsReportsRoute: DashboardInsightsReportsRoute,
  DashboardInsightsIndexRoute: DashboardInsightsIndexRoute,
};

const DashboardInsightsRouteWithChildren =
  DashboardInsightsRoute._addFileChildren(DashboardInsightsRouteChildren);

interface DashboardOutreachRouteChildren {
  DashboardOutreachRecallsRoute: typeof DashboardOutreachRecallsRoute;
  DashboardOutreachRemindersRoute: typeof DashboardOutreachRemindersRoute;
  DashboardOutreachIndexRoute: typeof DashboardOutreachIndexRoute;
}

const DashboardOutreachRouteChildren: DashboardOutreachRouteChildren = {
  DashboardOutreachRecallsRoute: DashboardOutreachRecallsRoute,
  DashboardOutreachRemindersRoute: DashboardOutreachRemindersRoute,
  DashboardOutreachIndexRoute: DashboardOutreachIndexRoute,
};

const DashboardOutreachRouteWithChildren =
  DashboardOutreachRoute._addFileChildren(DashboardOutreachRouteChildren);

interface DashboardSettingsClinicRouteChildren {
  DashboardSettingsClinicBrandingRoute: typeof DashboardSettingsClinicBrandingRoute;
  DashboardSettingsClinicComplianceRoute: typeof DashboardSettingsClinicComplianceRoute;
  DashboardSettingsClinicDetailsRoute: typeof DashboardSettingsClinicDetailsRoute;
  DashboardSettingsClinicHoursRoute: typeof DashboardSettingsClinicHoursRoute;
  DashboardSettingsClinicRoomsRoute: typeof DashboardSettingsClinicRoomsRoute;
  DashboardSettingsClinicIndexRoute: typeof DashboardSettingsClinicIndexRoute;
}

const DashboardSettingsClinicRouteChildren: DashboardSettingsClinicRouteChildren =
  {
    DashboardSettingsClinicBrandingRoute: DashboardSettingsClinicBrandingRoute,
    DashboardSettingsClinicComplianceRoute:
      DashboardSettingsClinicComplianceRoute,
    DashboardSettingsClinicDetailsRoute: DashboardSettingsClinicDetailsRoute,
    DashboardSettingsClinicHoursRoute: DashboardSettingsClinicHoursRoute,
    DashboardSettingsClinicRoomsRoute: DashboardSettingsClinicRoomsRoute,
    DashboardSettingsClinicIndexRoute: DashboardSettingsClinicIndexRoute,
  };

const DashboardSettingsClinicRouteWithChildren =
  DashboardSettingsClinicRoute._addFileChildren(
    DashboardSettingsClinicRouteChildren,
  );

interface DashboardSettingsOrganizationRouteChildren {
  DashboardSettingsOrganizationClinicsNewRoute: typeof DashboardSettingsOrganizationClinicsNewRoute;
}

const DashboardSettingsOrganizationRouteChildren: DashboardSettingsOrganizationRouteChildren =
  {
    DashboardSettingsOrganizationClinicsNewRoute:
      DashboardSettingsOrganizationClinicsNewRoute,
  };

const DashboardSettingsOrganizationRouteWithChildren =
  DashboardSettingsOrganizationRoute._addFileChildren(
    DashboardSettingsOrganizationRouteChildren,
  );

interface DashboardSettingsRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute;
  DashboardSettingsAssistantRoute: typeof DashboardSettingsAssistantRoute;
  DashboardSettingsClinicRoute: typeof DashboardSettingsClinicRouteWithChildren;
  DashboardSettingsDoctorRoute: typeof DashboardSettingsDoctorRoute;
  DashboardSettingsDocumentTemplatesRoute: typeof DashboardSettingsDocumentTemplatesRoute;
  DashboardSettingsMembershipPlansRoute: typeof DashboardSettingsMembershipPlansRoute;
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute;
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRouteWithChildren;
  DashboardSettingsPayersRoute: typeof DashboardSettingsPayersRoute;
  DashboardSettingsPlanRoute: typeof DashboardSettingsPlanRoute;
  DashboardSettingsServicesRoute: typeof DashboardSettingsServicesRoute;
  DashboardSettingsTeamRoute: typeof DashboardSettingsTeamRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsAssistantRoute: DashboardSettingsAssistantRoute,
  DashboardSettingsClinicRoute: DashboardSettingsClinicRouteWithChildren,
  DashboardSettingsDoctorRoute: DashboardSettingsDoctorRoute,
  DashboardSettingsDocumentTemplatesRoute:
    DashboardSettingsDocumentTemplatesRoute,
  DashboardSettingsMembershipPlansRoute: DashboardSettingsMembershipPlansRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsOrganizationRoute:
    DashboardSettingsOrganizationRouteWithChildren,
  DashboardSettingsPayersRoute: DashboardSettingsPayersRoute,
  DashboardSettingsPlanRoute: DashboardSettingsPlanRoute,
  DashboardSettingsServicesRoute: DashboardSettingsServicesRoute,
  DashboardSettingsTeamRoute: DashboardSettingsTeamRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
};

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren);

interface DashboardPatientsPatientIdDocumentsRouteChildren {
  DashboardPatientsPatientIdDocumentsNewRoute: typeof DashboardPatientsPatientIdDocumentsNewRoute;
}

const DashboardPatientsPatientIdDocumentsRouteChildren: DashboardPatientsPatientIdDocumentsRouteChildren =
  {
    DashboardPatientsPatientIdDocumentsNewRoute:
      DashboardPatientsPatientIdDocumentsNewRoute,
  };

const DashboardPatientsPatientIdDocumentsRouteWithChildren =
  DashboardPatientsPatientIdDocumentsRoute._addFileChildren(
    DashboardPatientsPatientIdDocumentsRouteChildren,
  );

interface DashboardPatientsPatientIdPrescriptionsRouteChildren {
  DashboardPatientsPatientIdPrescriptionsNewRoute: typeof DashboardPatientsPatientIdPrescriptionsNewRoute;
}

const DashboardPatientsPatientIdPrescriptionsRouteChildren: DashboardPatientsPatientIdPrescriptionsRouteChildren =
  {
    DashboardPatientsPatientIdPrescriptionsNewRoute:
      DashboardPatientsPatientIdPrescriptionsNewRoute,
  };

const DashboardPatientsPatientIdPrescriptionsRouteWithChildren =
  DashboardPatientsPatientIdPrescriptionsRoute._addFileChildren(
    DashboardPatientsPatientIdPrescriptionsRouteChildren,
  );

interface DashboardPatientsPatientIdRouteChildren {
  DashboardPatientsPatientIdActivityRoute: typeof DashboardPatientsPatientIdActivityRoute;
  DashboardPatientsPatientIdBillingRoute: typeof DashboardPatientsPatientIdBillingRoute;
  DashboardPatientsPatientIdDocumentsRoute: typeof DashboardPatientsPatientIdDocumentsRouteWithChildren;
  DashboardPatientsPatientIdOrdersRoute: typeof DashboardPatientsPatientIdOrdersRoute;
  DashboardPatientsPatientIdPrescriptionsRoute: typeof DashboardPatientsPatientIdPrescriptionsRouteWithChildren;
  DashboardPatientsPatientIdTimelineRoute: typeof DashboardPatientsPatientIdTimelineRoute;
  DashboardPatientsPatientIdIndexRoute: typeof DashboardPatientsPatientIdIndexRoute;
  DashboardPatientsPatientIdInvoicesInvoiceIdRoute: typeof DashboardPatientsPatientIdInvoicesInvoiceIdRoute;
  DashboardPatientsPatientIdInvoicesNewRoute: typeof DashboardPatientsPatientIdInvoicesNewRoute;
}

const DashboardPatientsPatientIdRouteChildren: DashboardPatientsPatientIdRouteChildren =
  {
    DashboardPatientsPatientIdActivityRoute:
      DashboardPatientsPatientIdActivityRoute,
    DashboardPatientsPatientIdBillingRoute:
      DashboardPatientsPatientIdBillingRoute,
    DashboardPatientsPatientIdDocumentsRoute:
      DashboardPatientsPatientIdDocumentsRouteWithChildren,
    DashboardPatientsPatientIdOrdersRoute:
      DashboardPatientsPatientIdOrdersRoute,
    DashboardPatientsPatientIdPrescriptionsRoute:
      DashboardPatientsPatientIdPrescriptionsRouteWithChildren,
    DashboardPatientsPatientIdTimelineRoute:
      DashboardPatientsPatientIdTimelineRoute,
    DashboardPatientsPatientIdIndexRoute: DashboardPatientsPatientIdIndexRoute,
    DashboardPatientsPatientIdInvoicesInvoiceIdRoute:
      DashboardPatientsPatientIdInvoicesInvoiceIdRoute,
    DashboardPatientsPatientIdInvoicesNewRoute:
      DashboardPatientsPatientIdInvoicesNewRoute,
  };

const DashboardPatientsPatientIdRouteWithChildren =
  DashboardPatientsPatientIdRoute._addFileChildren(
    DashboardPatientsPatientIdRouteChildren,
  );

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRouteWithChildren;
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute;
  DashboardBillingRoute: typeof DashboardBillingRouteWithChildren;
  DashboardChartSearchRoute: typeof DashboardChartSearchRoute;
  DashboardDocumentsRoute: typeof DashboardDocumentsRouteWithChildren;
  DashboardInsightsRoute: typeof DashboardInsightsRouteWithChildren;
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute;
  DashboardOutreachRoute: typeof DashboardOutreachRouteWithChildren;
  DashboardRecallsRoute: typeof DashboardRecallsRoute;
  DashboardRemindersRoute: typeof DashboardRemindersRoute;
  DashboardReportsRoute: typeof DashboardReportsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren;
  DashboardWaitingRoomRoute: typeof DashboardWaitingRoomRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardPatientsPatientIdRoute: typeof DashboardPatientsPatientIdRouteWithChildren;
  DashboardPatientsChartSearchRoute: typeof DashboardPatientsChartSearchRoute;
  DashboardPatientsNewRoute: typeof DashboardPatientsNewRoute;
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRouteWithChildren,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardBillingRoute: DashboardBillingRouteWithChildren,
  DashboardChartSearchRoute: DashboardChartSearchRoute,
  DashboardDocumentsRoute: DashboardDocumentsRouteWithChildren,
  DashboardInsightsRoute: DashboardInsightsRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOutreachRoute: DashboardOutreachRouteWithChildren,
  DashboardRecallsRoute: DashboardRecallsRoute,
  DashboardRemindersRoute: DashboardRemindersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardWaitingRoomRoute: DashboardWaitingRoomRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPatientsPatientIdRoute: DashboardPatientsPatientIdRouteWithChildren,
  DashboardPatientsChartSearchRoute: DashboardPatientsChartSearchRoute,
  DashboardPatientsNewRoute: DashboardPatientsNewRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

interface PlatformRouteChildren {
  PlatformFlagsRoute: typeof PlatformFlagsRoute;
  PlatformMetricsRoute: typeof PlatformMetricsRoute;
  PlatformIndexRoute: typeof PlatformIndexRoute;
  PlatformTenantsClinicIdRoute: typeof PlatformTenantsClinicIdRoute;
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformFlagsRoute: PlatformFlagsRoute,
  PlatformMetricsRoute: PlatformMetricsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformTenantsClinicIdRoute: PlatformTenantsClinicIdRoute,
};

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BookSlugRoute: BookSlugRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  NpsTokenRoute: NpsTokenRoute,
  ReferralChartTokenRoute: ReferralChartTokenRoute,
  RemindersTokenRoute: RemindersTokenRoute,
  PatientPortalSlugChartRoute: PatientPortalSlugChartRoute,
  PatientPortalSlugDocumentsRoute: PatientPortalSlugDocumentsRoute,
  PatientPortalSlugInvoicesRoute: PatientPortalSlugInvoicesRoute,
  PatientPortalSlugLoginRoute: PatientPortalSlugLoginRoute,
  PatientPortalSlugVerifyRoute: PatientPortalSlugVerifyRoute,
  PatientPortalSlugVisitsRoute: PatientPortalSlugVisitsRoute,
  PatientPortalSlugIndexRoute: PatientPortalSlugIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
