/** Generic form placeholders. Avoid real patient names or clinic identifiers. */
export const FORM_PLACEHOLDERS = {
  fullName: "Ex. Juan Dela Cruz",
  email: "clinic@example.com",
  phone: "Ex. 0917 123 4567",
  clinicName: "Ex. Riverside Clinic",
  condition: "Ex. Hypertension",
  address: "Ex. 12 Rizal St, Quezon City",
  license: "Ex. PRC 1234567",
  memberId: "Ex. HMO-001234",
  hmo: "Ex. Maxicare",
  occupation: "Ex. Teacher",
  reasonForVisit: "Ex. Follow-up consult",
  drugName: "Ex. Amoxicillin",
  dosage: "Ex. 500 mg",
  frequency: "Ex. 3 times daily",
  duration: "Ex. 7 days",
  quantity: "Ex. 21 capsules",
  invoiceLine: "Ex. Consultation",
  serviceName: "Ex. Consultation",
  serviceCategory: "Ex. Consult",
  templateName: "Ex. Medical certificate",
  templateKey: "Ex. medcert-standard",
  roomName: "Ex. Room 1",
  orderName: "Ex. CBC",
  icdSearch: "Ex. J06.9",
  soapSubjective: "Chief complaint and history",
  soapObjective: "Exam findings and vitals",
  soapAssessment: "Working diagnosis",
  soapPlan: "Treatment and follow-up",
  diagnosis: "Ex. Acute URTI",
  searchPatients: "Search name, contact, ID",
  searchInvoices: "Search invoice or patient",
  searchAppointments: "Search patient or doctor",
  searchCharts: "Search charts",
  overrideReason: "Why this prescription is still issued",
  referralRecipient: "Ex. Dr. Reyes, PGH ENT",
  vaccine: "Ex. 2024-06-01 Flu",
  mergePatientId: "Source patient ID",
} as const;
